### ISSUE TITLE
Module "monome" has the same name as the libmonome module

### ISSUE THREAD

**Issue by simonvanderveldt** [artfwo/pymonome#4]
First of all, thanks for this project! Although the async stuff is new to me, the grid studies were a very nice intro, really liking it so far!

Anyway, I wanted to discuss something. The module as it's importable within Python is called `monome`, which is the same name as the name of the module for the Python bindings for libmonome, which is kind of unfortunate.
What do you think would be the best fix for this?

**Comment by artfwo** [comment]
Not sure about this. I never used Python bindings for libmonome myself and don't think the library is actually used by many projects without serialosc. Do you have any suggestions for renaming?

**Comment by simonvanderveldt** [comment]
> Not sure about this. I never used Python bindings for libmonome myself and don't think the library is actually used by many projects without serialosc. Do you have any suggestions for renaming?

Not really. Would it be possible/and option to add this module to libmonome or does that not really make sense?

**Comment by artfwo** [comment]
It is possible, but the libraries are very different and it's better to keep the code separate.

**Comment by simonvanderveldt** [comment]
Discussed this on irc with @wrl and he's ok with to the option of removing the python bindings from libmonome and referring people who want to build a monome/serialosc app using python to pymonome. Libmonome's Python bindings haven't received much love according to him and this way we have one clear option for anyone who wants to build a monome app in Python which benefits us all :)

Since pymonome is already used in the grid studies, which are basically the starting point for anyone writing a monome app, it is already the de facto standard, this change would just solidify that choice.
I'll create a PR in https://github.com/monome/libmonome to remove the python bindings and update the docs and we should be good to go :)
